#!/bin/sh

# Wait until D-Bus is up and the init script has mapped in the external hostname
until [ -e /var/run/dbus/system_bus_socket ] && [ -e /var/run/avahi_configured ]; do
  echo "Wait until D-Bus is up..."
  sleep 1s
done

echo "Starting Avahi daemon..."
exec avahi-daemon